# This is a basic workflow to help you get started with Actions

name: CI

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate a Pull Request
    steps:
      - uses: actions/checkout@v1

      - name: Validate SRCINFO
        id: validate-srcinfo
        uses: ./.github/actions/pkgbuild
        with:
          target: 'srcinfo'
          pkgname: "zls-git"

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: ./.github/actions/pkgbuild
        with:
          target: 'pkgbuild'
          pkgname: "zls-git"

      - name: Prepare tools
        run: |
          wget -O ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
          tar -xvf ghr.tar.gz
          mv ghr*linux_amd64/ghr .

      - name: Release packages 
        run: |
          ./ghr -t "${{ github.token }}" -n "${{ github.event.release.tag_name }}" "${{ github.event.release.tag_name }}" artifacts
